version: '3.8'

services:
  mysql:
    image: mysql:8.0.33
    container_name: mysql_db_crm
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: crm
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d

  app:
    build: .  # Utilise le Dockerfile pour construire l'image
    container_name: spring_boot_app_crm
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/crm
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root

volumes:
  mysql_data: